import { FormData } from "@/components/email";
export interface Item{
    id: Number,
    numThumbs: Number,
    material: String,
    glaze: String,
    year: String,
    method: String
  }

export function sendEmail(data: FormData){
   const apiEndpoint = "/api/email";
   fetch(apiEndpoint, {
     method: "POST",
     body: JSON.stringify(data),
   })
     .then((res) => res.json())
     .then((response) => {
       alert(response.message);
     })
     .catch((err) => {
       alert(err);
     });
}

export const allItems: Item[] = [
  {
    id: 1,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white/black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 2,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin oribe",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 3,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white, blue lagoon",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 4,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white/black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 5,
    numThumbs: 2,
    material: "porcelain",
    glaze: "celadon black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 6,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white/black mix",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 7,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white, satin oribe",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 8,
    numThumbs: 3,
    material: "porcelain",
    glaze: "satin matte white/black mix",
    method: "wheel-thrown",
    year: "2021",
  },
  {
    id: 9,
    numThumbs: 4,
    material: "porcelain",
    glaze: "shino acai matte, iron lustre, toasted sage",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 10,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white/black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 11,
    numThumbs: 1,
    material: "porcelain",
    glaze: "celadon black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 12,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white/black/teal mix",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 13,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 14,
    numThumbs: 3,
    material: "porcelain",
    glaze: "seaweed",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 15,
    numThumbs: 2,
    material: "porcelain",
    glaze: "celadon black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 16,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white, satin oribe",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 17,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white/black mix",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 18,
    numThumbs: 1,
    material: "porcelain",
    glaze: "textured turquoise, celadon black, snow",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 19,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white, blue lagoon",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 20,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 21,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white, blue lagoon",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 22,
    numThumbs: 1,
    material: "porcelain",
    glaze: "celadon black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 23,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white, blue lagoon",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 24,
    numThumbs: 1,
    material: "porcelain",
    glaze: "shino acai matte",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 25,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin oribe",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 26,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white, seaweed",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 27,
    numThumbs: 1,
    material: "porcelain",
    glaze: "unknown",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 28,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white, celadon black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 29,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white, blue lagoon",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 30,
    numThumbs: 1,
    material: "porcelain",
    glaze: "satin matte white/black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 31,
    numThumbs: 3,
    material: "porcelain",
    glaze: "satin matte white/black",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 32,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white, blue lagoon",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 33,
    numThumbs: 2,
    material: "porcelain",
    glaze: "satin matte white",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 34,
    numThumbs: 1,
    material: "porcelain",
    glaze: "matcha gloss",
    method: "wheel-thrown",
    year: "2023",
  },
  {
    id: 35,
    numThumbs: 3,
    material: "white stoneware",
    glaze: "black underglaze, textured turquoise, celadon black",
    method: "hand-built",
    year: "2023",
  },
  {
    id: 36,
    numThumbs: 1,
    material: "white stoneware",
    glaze: "black underglaze, textured turquoise, celadon black",
    method: "hand-built",
    year: "2023",
  },
];