export interface Item{
    id: Number,
    numThumbs: Number,
    material: String,
    glaze: String,
    year: String,
    method: String
  }



export const allItems: Item[] = [
  {
    id: 1,
    numThumbs: 2,
    material: "porcelain",
    glaze: "white and black",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 2,
    numThumbs: 2,
    material: "porcelain",
    glaze: "blue",
    method: "hand-thrown",
    year: "2024",
  },
  {
    id: 3,
    numThumbs: 2,
    material: "clay",
    glaze: "black",
    method: "hand-thrown",
    year: "2024",
  },
  {
    id: 4,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2024",
  },
  {
    id: 5,
    numThumbs: 2,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 6,
    numThumbs: 2,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 7,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 8,
    numThumbs: 3,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 9,
    numThumbs: 4,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 10,
    numThumbs: 2,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 11,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 12,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 13,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 14,
    numThumbs: 3,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 15,
    numThumbs: 2,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 16,
    numThumbs: 2,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 17,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 18,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 19,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 20,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 21,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 22,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 23,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 24,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 25,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 26,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 27,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 28,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 29,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 30,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 31,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 32,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 33,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 34,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 35,
    numThumbs: 3,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
  {
    id: 36,
    numThumbs: 1,
    material: "white clay",
    glaze: "white",
    method: "hand-thrown",
    year: "2023",
  },
];